// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_OEhv40FIuXaefo9on-_O4XSYc6X5yw',
    appId: '1:560971488530:android:5e17a65ca117c5b8bda7cb',
    messagingSenderId: '560971488530',
    projectId: 'scheduleme-adde6',
    databaseURL: 'https://scheduleme-adde6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scheduleme-adde6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PRyMskWbTY6hWdkKTvo84IDmo3emuJY',
    appId: '1:560971488530:ios:d6b4e862a3bea7cabda7cb',
    messagingSenderId: '560971488530',
    projectId: 'scheduleme-adde6',
    databaseURL: 'https://scheduleme-adde6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scheduleme-adde6.appspot.com',
    iosClientId: '560971488530-onjipaom4goc492ahjl1sf1kqct1b4dp.apps.googleusercontent.com',
    iosBundleId: 'com.entropy.scheduleme',
  );
}
